<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
	<meta name="description" content=""/>
	<meta name="viewport" content="width=device-width"/>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->HeadMeta(); ?>
    <?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
</head>
<body>
	<?php echo $this->layout()->content; ?>
</body>
</html>