<style tyle="text/css">
	h2 {font-size:20px;}
	a:focus,a:hover {color:#FFF;text-decoration:none;}
	div.container{}
	span.button { border:1px solid #333;padding:5px 20px;text-align:center;position:absolute;left:8px;background-color:#999; }
	span.button2 { border:1px solid #fff;padding:7px 20px;text-align:center;background-color:#000;color:#FF0000;font-weight:bold;}
	.submission-form input[type="text"]{width:186px;height:20px;border:1px solid #cccccc;padding:3px 5px;color:#3333CC;}
	.submission-form input[type="password"]{width:186px;height:20px;border:1px solid #cccccc;padding:3px 5px;color:#3333CC;}
	.submission-form input[type="submit"]{border:1px solid #cccccc;padding:3px 5px;color:#333;font-weight:bold;}
	.right {float:right;}
	div.msg {clear:both;margin-left:20px;color:#FF0000;float:right;}
</style>
<div style="position:absolute;top:30px;">
	<?php if( Zend_Session::namespaceIsset($this->sessionKey) ): ?>
		<div style="width:650px;height:auto;position:absolute;left:50px;top:30px;margin:30px 0 0 25px;">
			<h2>Download contest report (Rock That Tick)</h2>
			<a href="<?php echo $this->baseUrl.'/report/logout'; ?>" style="position:absolute;right:0;top:0"><span class="button2 right">Log out</span></a>
			<br>
			<a href="<?php echo $this->baseUrl.'/report/submissionsdetail'; ?>"><span class="button">Submission detail list</span></a>
			<br><br>
			<a href="<?php echo $this->baseUrl.'/report/mostvoted'; ?>"><span class="button">Most voted submissions list</span></a>
		</div>
	<?php else: ?>
		<div style="width:650px;height:auto;position:absolute;left:50px;top:30px;">
			<form class="submission-form" method="POST">

				<table style="width:100%;margin:30px 0 0 25px;">
					<tr>
						<td colspan="2">
							<h2>Login to Download contest report (Rock That Tick)</h2>
						</td>
					</tr>
					<tr>
						<td><label>Username</label></td>
						<td>
							<input name="username" type="text"/><br/><br/>
						</td>
					</tr>
					<tr>
						<td><label>Password</label></td>
						<td>
							<input name="password" type="password"/><br/><br/>
						</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>
							<input name="submit" type="submit" value="Log in"/>
						</td>
					</tr>
				</table>

				<?php if( !empty($this->message) ): ?>
					<div class="msg"><?php echo $this->message; ?></div>
				<?php endif; ?>
			</form>
		</div>
	<?php endif; ?>
</div>